language: python

python:
  - "3.6.7"

addons:
  postgresql: "11"

services:
  - postgresql


install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
        - psql -c "create database backend_blog;" -U postgres

script:
        - python manage.py db init
        - python manage.py migrate
        - python3 manage.py db upgrade
        - python3 manage.py test
        - flake8 api

