language: python

python:
  - "3.6.7"

addons:
  postgresql: "11"

services:
  - postgresql


install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
        - sudo apt-get update
        - sudo apt-get install --yes postgresql-server-dev-11
        - sudo /etc/init.d/postgresql restart
        - psql -c "create database backend_blog;" -U postgres
        - cd src

script:
        - python manage.py db init
        - python manage.py migrate
        - python3 manage.py db upgrade
        - python3 manage.py test
        - flake8 api --ignore E402

