language: python

python:
  - "3.6.7"

addons:
  postgresql: "11"

services:
  - postgresql


install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
        - sudo apt-get update
        - sudo apt-get install --yes postgresql-server-dev-11
        - sudo /etc/init.d/postgresql restart
        - psql -c "create database backend_blog_test;" -U postgres
        - cd src
        - python3 manage.py test
        - python3 manage.py cov

script:
        - flake8 api --ignore E402

after_success:
  - coveralls
